# Generated by Django 4.2.5 on 2023-11-06 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='is_locked',
            new_name='is_locked_flag',
        ),
    ]
