# Generated by Django 4.2.5 on 2024-01-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_rename_is_locked_article_is_locked_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotLockedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of this instance.', max_length=120, verbose_name='name')),
            ],
        ),
    ]
