# Generated by Django 4.2.5 on 2023-12-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NonLockableArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of this article.', max_length=120, verbose_name='title')),
                ('is_locked_flag', models.BooleanField(default=False, help_text='Whether this article is locked or not.', verbose_name='is locked')),
            ],
        ),
    ]
