# Generated by Django 4.2.5 on 2023-12-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles_nonlockable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotImplementedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'not implemented',
                'verbose_name_plural': 'not implemented',
            },
        ),
    ]
